# Generated by Django 5.1.2 on 2024-10-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genNombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelCodigo', models.CharField(max_length=9)),
                ('pelTitulo', models.CharField(max_length=50)),
                ('pelProtagonista', models.CharField(max_length=50)),
                ('pelDuracion', models.IntegerField()),
                ('pelResumen', models.CharField(max_length=2000)),
                ('pelFoto', models.ImageField(upload_to='uploads/peliculas/')),
                ('pelGenero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPeliculas.genero')),
            ],
        ),
    ]
